### ISSUE TITLE
Incorrect delta-v bounds on colormap

### ISSUE THREAD

**Issue by simon-b** [alexmoon/ksp#10]
For certain results, the delta-v transfer plot colormap is mostly blue, and according to the scale the red color should correspond to some very large delta-v that doesn't appear on the map.  
For example, Kerbin 100km -> Duna 100km from year 1 day 1, mid-course plane change. The delta-v scale is from 1668 m/s (blue) to 765060 m/s (red). But the highest delta-v visible on the plot is around 20000 m/s

**Comment by alexmoon** [comment]
Fixed.
