### ISSUE TITLE
Date wrapping around year 76?

### ISSUE THREAD

**Issue by pem** [alexmoon/ksp#12]
My KSP date is now in year 74, and the otherwise excellent launch window calculator seems to break down. Somewhere around the year 76 the days since epoch seems to wrap, and it starts first to count the day axis in descending order, and further away into the future the graph becomes a mess and it suggests launch dates in year 5 and similar.

**Comment by alexmoon** [comment]
Are you using Kerbal Time or Earth Time?

**Comment by pem** [comment]
Kerbal time.

**Comment by alexmoon** [comment]
Should be fixed now.
