### ISSUE TITLE
It does not calculate for custom orbit

### ISSUE THREAD

**Issue by Shpigorx** [alexmoon/ksp#16]
As I understand, I can customize my current orbit in Edit Orbit / Vessel.
I choose:
Origin: Mun
[Vessel]
- Semi-Major: 272.566 km
- Eccentricity: 0.036
- Inclination 101.19
- Longitude: 79.43
- Argument PE: 210
- Time: 1/52 5:38:00 (as I understand, it's time when I'll be in Periapsis)

Destination: Minmus
Checked "No insertion..."
Earliest departure: y1 d52, Ballistic

Click on "Plot it" and nothing happens. On image Departure days have 51 and White graph. There is no dV.
Also when First time "Time of periapsis passage" is blank and clicking Save, Red border and Caption are shown, after entering values still shows border and do not save.

**Comment by alexmoon** [comment]
Fixed.

**Comment by mark-c** [comment]
Doesn't work for me, at least with my info (and I checked the advanced info to make everything fall in range to avoid any potential non-checks with the dates).
