### ISSUE TITLE
Not validating or parsing dates

### ISSUE THREAD

**Issue by HairyDude** [alexmoon/ksp#17]
(Using the website)

I'm trying to calculate transfer windows for a kerbal trapped in orbit around the sun (spawned by a contract). I've got all the orbit info from the save's persistent.sfs, apart from time of periapsis passage. No matter what I enter in the "time of periapsis passage" field, it gets reset to 1/1 0:00:NaN (you can see this if you click save, then close and reopen the edit orbit form).

Looking at celestialbodyform.coffee, it seems the form should be validating the date, but no error is shown no matter what I put there. "foo bar baz" gives no error, for example.

**Comment by Korvar** [comment]
I'm getting the same error.

**Comment by alexmoon** [comment]
Fixed.
