### ISSUE TITLE
Suggestion: Calendar view

### ISSUE THREAD

**Issue by ScottTFrazer** [alexmoon/ksp#2]
First: Thank you for your effort with the KSP, very nice looking and useful site.

I had an idea that I am just not a good enough coder to implement myself: A Calendar view.

Use the calculations you have to determine the dark blue zones on the transfer points, then check each day for which celestial bodies are dark blue.

Since this stuff doesn't really change from game run to game run, you could pre-calculate about 10 years of Kerbal time fairly quickly, I think.

**Comment by alexmoon** [comment]
I think someone's already taken care of this. Check out: http://www.reddit.com/r/KerbalAcademy/comments/1qt764/a_compiled_list_of_optimal_interplanetary/
