### ISSUE TITLE
I can't select a destination or plot a graph when I add a custom vessel orbit.

### ISSUE THREAD

**Issue by mark-c** [alexmoon/ksp#22]
Hi Alex, I am looking forward to using your planner for a tour mission trip that will meet up with my (first!) fuel and mining station that is waiting for a good window to Minmus. ----BEGIN Walloftext--  However, I have a peculiar orbit (somehow the lander overshot on surface escape and I decided to make the orbiter catch up instead of "cheating" fuel to get back to an orbit I already covered), which is 10x120 roughly and oriented with the large end of SMA toward Kerbin. Minmus is in a very difficult position, almost directly in line with the PA. I calculate there are about 1353 m/s absolute max. including the lander's fuel, with none left for Vernor RCS, but I digress. Technically it should be enough to get to Kerbin SOI edge and Minmus, but I would rather meet with the station first.
--END Walloftext--

After copying my orbital data (thank goodness I have a mod now) into an added "Vessel" origin body, the "Destination" option is blocked and clicking "Plot" does nothing. In other words, something broke and I don't know how to get around it or find the info I need without my peculiar orbit data.

**Comment by alexmoon** [comment]
The planner can only calculate transfers between two orbits around a common central body. If your vessel is orbiting Minmus, the only valid destination would be another vessel orbiting Minmus. You should be able to plot a transfer from a vessel orbiting Kerbin to the Mun or Minmus, or a vessel in solar orbit to any of the planets, etc.
