### ISSUE TITLE
NAN values diplayed

### ISSUE THREAD

**Issue by gernstsmit** [alexmoon/ksp#23]
First I would like to thank you for this awesome tool ! I always use this for all my KSP interplanetary missions.

I seem to have found a bug. When I input these variables:
https://alexmoon.github.io/ksp/#/Dres/70000/Kerbin/71/false/optimal/false/13/100

the following values display NaN:
1) Ejection angle
2) Ejection inclination
3) Prograde dV *
4) Normal dV
5) Heading

* Note: an ejection dV is given at 1668m/s

This has never happened to me before, though you might want to know.

Best Wishes
Ernst Smit
E-mail: gernstsmit@gmail.com

**Comment by alexmoon** [comment]
Your starting orbit of 70,000km is outside of Dres' sphere of influence so the ejection parameters have no meaning.
