### ISSUE TITLE
May I use your orbit class as a library?

### ISSUE THREAD

**Issue by DavidSouther** [alexmoon/ksp#5]
Because holy wow, that is some of the most elegant Coffee I've seen. :+1:

**Comment by alexmoon** [comment]
Sure, you're free to use it under the CC BY-SA-NC license. Be aware that there are a few dependencies on celestialbodies.coffee and lambert.coffee, but they would be pretty easy to rip out if you don't want those. You will definitely need the numeric.js library. Mind if I ask what you plan to use it for?

**Comment by DavidSouther** [comment]
I'm working on a near-future space combat game. Think KSP meets Star Trek. https://github.com/DavidSouther/sns

Yeah, I saw the other dependencies, shouldn't have a problem pulling them in. Thanks for pointing out numeric.js!
